import { Inter_Tight } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/home/Navbar";

const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: { icon: "/startech.svg" },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${interTight.variable} font-inter antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
